server:
  port: 8085

spring:
  application:
    name: email-service

  rabbitmq:
    host: rabbitmq
    port: 5672

  mail:
    host: smtp.gmail.com
    port: 587
    username: ${SPRING_MAIL_USERNAME:${MAIL_USERNAME:}}
    password: ${SPRING_MAIL_PASSWORD:${MAIL_PASSWORD:}}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

# Proprietăți aplicație
app:
  confirm-base-url: ${APP_CONFIRM_BASE_URL:http://localhost:8080/api/auth/confirm}
  mail:
    from: ${APP_MAIL_FROM:}

logging:
  level:
    org.springframework.mail: INFO
