spring:
  application:
    name: email-service

  rabbitmq:
    host: rabbitmq
    port: 5672

  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
