version: "3.8"

services:
  auth-service:
    build:
      context: .
      dockerfile: ./auth-service/Dockerfile
    depends_on:
      - rabbitmq
      - postgres

  app-service:
    build:
      context: .
      dockerfile: ./app-service/Dockerfile
    depends_on:
      - postgres

  donations-service:
    build:
      context: .
      dockerfile: ./donations-service/Dockerfile
    depends_on:
      - postgres

  gateway:
    build:
      context: .
      dockerfile: ./gateway/Dockerfile

  email-service:
    build:
      context: .
      dockerfile: ./email-service/Dockerfile
    depends_on:
      - rabbitmq

  rabbitmq:
    image: rabbitmq:3-management

  postgres:
    image: postgres:15
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: viitorul-rachiteni
    volumes:
      - postgres_data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4:latest
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@gmail.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    volumes:
      - pgadmin:/var/lib/pgadmin
    depends_on:
      - postgres
    restart: unless-stopped

volumes:
  postgres_data:
  pgadmin:
