version: "3.8"

services:
  auth-service:
    build:
      context: .
      dockerfile: ./auth-service/Dockerfile
    ports:
      - "8081:8081"
    env_file:
      - ./auth-service/.env
    depends_on:
      - rabbitmq

  app-service:
    build:
      context: .
      dockerfile: ./app-service/Dockerfile
    ports:
      - "8082:8082"
    env_file:
      - ./app-service/.env

  donations-service:
    build:
      context: .
      dockerfile: ./donations-service/Dockerfile
    ports:
      - "8083:8083"
    env_file:
      - ./donations-service/.env

  gateway:
    build:
      context: .
      dockerfile: ./gateway/Dockerfile
    ports:
      - "8080:8080"
    env_file:
      - ./gateway/.env

  email-service:
    build:
      context: .
      dockerfile: ./email-service/Dockerfile
    ports:
      - "8085:8085"
    env_file:
      - ./email-service/.env
    depends_on:
      - rabbitmq

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"
