server:
  port: 8080

spring:
  cloud:
    compatibility-verifier:
      enabled: false
    gateway:
      globalcors:
        add-to-simple-url-handler-mapping: true
        corsConfigurations:
          '[/**]':
            allowedOrigins: "http://localhost:5173"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS
            allowedHeaders:
              - "*"
            allowCredentials: true

      routes:
        - id: auth-service
          uri: http://auth-service:8081
          predicates:
            - Path=/api/auth/**

        - id: app-service
          uri: http://app-service:8082
          predicates:
            - Path=/api/app/**

        - id: donations-service
          uri: http://donations-service:8083
          predicates:
            - Path=/donations/**

        - id: email-service
          uri: http://email-service:8085
          predicates:
            - Path=/api/email/**

        - id: oauth2-auth
          uri: http://auth-service:8081
          predicates:
            - Path=/oauth2/authorization/**
          filters:
            - RewritePath=/oauth2/authorization/(?<segment>.*), /oauth2/authorization/${segment}
            - SetStatus=302

        - id: oauth2-login
          uri: http://auth-service:8081
          predicates:
            - Path=/login/oauth2/**
          filters:
            - RewritePath=/login/oauth2/(?<segment>.*), /login/oauth2/${segment}

        - id: oauth2-callback
          uri: http://auth-service:8081
          predicates:
            - Path=/oauth2/**
          filters:
            - RewritePath=/oauth2/(?<segment>.*), /oauth2/${segment}

      default-filters:
        - AddResponseHeader=X-Gateway, Viitorul
      preserveHostHeader: true
