spring:
  config:
    activate:
      on-profile: dev

  cloud:
    gateway:
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - http://localhost:5173
            allowedMethods: [ GET, POST, PUT, PATCH, DELETE, OPTIONS ]
            allowedHeaders: "*"
            exposedHeaders: [ Authorization, Set-Cookie ]
            allowCredentials: true
