server:
  port: 8080
  forward-headers-strategy: framework

spring:
  cloud:
    compatibility-verifier:
      enabled: false
    gateway:
      preserveHostHeader: true
      default-filters:
        - AddResponseHeader=X-Gateway, Viitorul
        - DedupeResponseHeader=Access-Control-Allow-Origin Access-Control-Allow-Credentials

      routes:
        # ===== API cu prefix /api =====

        # /api/auth/** -> auth-service: expune de regulă /auth/**
        - id: auth-api
          uri: http://auth-service:8081
          predicates:
            - Path=/api/auth/**

        # /api/app/** -> app-service: de regulă expune /ads, /players etc.
        - id: app-api
          uri: http://app-service:8082
          predicates:
            - Path=/api/app/**

        # /api/donations/** -> donations-service
        - id: donations-api
          uri: http://donations-service:8083
          predicates:
            - Path=/api/donations/**
          filters:
            - StripPrefix=2

        # /api/email/** -> email-service
        - id: email-api
          uri: http://email-service:8085
          predicates:
            - Path=/api/email/**
          filters:
            - StripPrefix=1

        # ===== OAuth2 FĂRĂ prefix (/oauth2/** și /login/oauth2/**) =====
        - id: oauth2-start
          uri: http://auth-service:8081
          predicates:
            - Path=/oauth2/**
          filters:
            - PreserveHostHeader

        - id: oauth2-callback
          uri: http://auth-service:8081
          predicates:
            - Path=/login/oauth2/**
          filters:
            - PreserveHostHeader
management:
  endpoints:
    web:
      exposure:
        include: gateway,health,info