server:
  port: 8080
  forward-headers-strategy: framework

spring:
  cloud:
    compatibility-verifier:
      enabled: false
    gateway:
      # CORS global
      globalcors:
        corsConfigurations:
          '[/**]':
            # listă separată prin virgulă din env; dacă nu există, folosește valorile de mai jos
            allowedOrigins: ${ALLOWED_ORIGINS:https://www.viitorulrachiteni.ro,https://viitorulrachiteni.ro,http://localhost:5173}
            allowedMethods:
              - GET
              - POST
              - PUT
              - PATCH
              - DELETE
              - OPTIONS
            allowedHeaders: "*"
            exposedHeaders:
              - Authorization
              - Set-Cookie
            allowCredentials: true

      # Rute
      routes:
        # API-urile serviciului de autentificare (/api/auth/**)
        - id: auth-api
          uri: http://auth-service:8081
          predicates:
            - Path=/api/auth/**

        # API-urile aplicației (/api/app/**)
        - id: app-api
          uri: http://app-service:8082
          predicates:
            - Path=/api/app/**

        # Donatii (păstrează exact cum ai în backend)
        - id: donations-api
          uri: http://donations-service:8083
          predicates:
            - Path=/donations/**

        # Email API
        - id: email-api
          uri: http://email-service:8085
          predicates:
            - Path=/api/email/**

        # TOATE rutele OAuth prin prefixul /auth/**
        # /auth/login/oauth2/**, /auth/oauth2/authorization/**, etc.
        - id: auth-oauth
          uri: http://auth-service:8081
          predicates:
            - Path=/auth/**
          filters:
            - StripPrefix=1

      default-filters:
        - AddResponseHeader=X-Gateway, Viitorul
        # previne dublarea headerelor CORS
        - DedupeResponseHeader=Access-Control-Allow-Origin Access-Control-Allow-Credentials
      preserveHostHeader: true
