server:
  port: 8080

spring:
  cloud:
    compatibility-verifier:
      enabled: false
    gateway:
      server:
        webflux:
          routes:
            - id: auth-service
              uri: http://auth-service:8081
              predicates:
                - Path=/api/auth/**
            - id: user-service
              uri: http://user-service:8082
              predicates:
                - Path=/users/**
            - id: donations-service
              uri: http://donations-service:8083
              predicates:
                - Path=/donations/**
          default-filters:
            - AddResponseHeader=X-Gateway, Viitorul
