server:
  port: 8080
  forward-headers-strategy: framework

spring:
  cloud:
    compatibility-verifier:
      enabled: false
    gateway:
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: ${ALLOWED_ORIGINS:https://www.viitorulrachiteni.ro,https://viitorulrachiteni.ro,http://localhost:5173}
            allowedMethods: [ GET, POST, PUT, PATCH, DELETE, OPTIONS ]
            allowedHeaders: "*"
            exposedHeaders: [ Authorization, Set-Cookie ]
            allowCredentials: true

      routes:
        - id: auth-api
          uri: http://auth-service:8081
          predicates:
            - Path=/api/auth/**

        - id: app-api
          uri: http://app-service:8082
          predicates:
            - Path=/api/app/**

        - id: donations-api
          uri: http://donations-service:8083
          predicates:
            - Path=/donations/**

        - id: email-api
          uri: http://email-service:8085
          predicates:
            - Path=/api/email/**

        # 1) Direct: /oauth2/** și /login/oauth2/** merg fără rewrite
        - id: oauth-direct
          uri: http://auth-service:8081
          predicates:
            - Path=/oauth2/**,/login/oauth2/**

        # 2) Compat: /auth/** se rescrie la rădăcină (păstrăm varianta cu prefix)
        - id: oauth-prefixed
          uri: http://auth-service:8081
          predicates:
            - Path=/auth/**
          filters:
            - RewritePath=/auth/(?<segment>.*), /${segment}

      default-filters:
        - AddResponseHeader=X-Gateway, Viitorul
        - DedupeResponseHeader=Access-Control-Allow-Origin Access-Control-Allow-Credentials
      preserveHostHeader: true
