spring:
  application:
    name: donations-service

  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
    properties:
      hibernate.jdbc.time_zone: UTC

server:
  port: 8083

stripe:
  secret-key: ${STRIPE_SECRET_KEY}
  webhook-secret: ${STRIPE_WEBHOOK_SECRET}

donations:
  success-url: https://www.viitorulrachiteni.ro/donations/success
  cancel-url:  https://www.viitorulrachiteni.ro/donations/cancel
  default-currency: ron
  name: "Donație ACS Viitorul Răchiteni"
